### ISSUE TITLE
Index zeigt nicht alle Gruppen an (Contao 3.2.x auf XAMPP/Win7)

### ISSUE THREAD

**Issue by nkirstein** [netzmacht/contao-language-editor#1]
Wenn Contao auf XAMPP unter Windows 7 läuft, werden beim Aufbau des Index der Sprachdateien nur die fest codierten Gruppen indiziert.

**Comment by dmolineus** [comment]
I made some changes provided in the develop branch. Would be nice If you can test it using Windows. Unfortunately I don't have a windows setup here.

**Comment by nkirstein** [comment]
It works now, at least on my system. Thanks for fixing this!

**Comment by dmolineus** [comment]
Thanks for testing. Will be released in the next minor version.
